GET http://localhost:5000/


###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "te@gmail.com",
    "password": "helloworld"
}

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "123",
    "email": "te@gmail.com",
    "password": "helloworld"
}


###
GET http://localhost:5000/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJ0ZUBnbWFpbC5jb20iLCJpYXQiOjE3Mzc1OTAwOTcsImV4cCI6MTczNzYwMDg5N30.YyOp03o4yv5jEDSJARW8HpI4cZP6imGHTYGjI_zgBhk


###
GET http://localhost:5000/testauth
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Z3Vlc3Q.YEeLF3Xr-qFI76PRvUDQ4jsd_FPBShivl1YDs9kpEPY


###
GET http://localhost:5000/navigate/

###
GET http://localhost:5000/navigate/first
