GET http://localhost:5000/


###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "secretadmin"
}

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "secretadmin"
}


###
GET http://localhost:5000/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3Mzc2Mzc3MjIsImV4cCI6MTczNzY0ODUyMn0.2UQi_Jphxy0O69bHXVhCVXMoBufT6p5TnMfE-MTggpc


###
GET http://localhost:5000/testauth
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Z3Vlc3Q.YEeLF3Xr-qFI76PRvUDQ4jsd_FPBShivl1YDs9kpEPY


###
GET http://localhost:5000/navigate/

###
GET http://localhost:5000/navigate/first

###
GET http://localhost:5000/files/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3Mzc2Mzc3MjIsImV4cCI6MTczNzY0ODUyMn0.2UQi_Jphxy0O69bHXVhCVXMoBufT6p5TnMfE-MTggpc