GET http://localhost:5000/


###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "secretadmin"
}

###
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username": "admian",
    "email": "admian@gmail.com",
    "password": "secretadmin"
}


###
GET http://localhost:5000/user/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3Mzc2NzY5ODQsImV4cCI6MTczNzY4Nzc4NH0.MPDKoobrgN2Cnzd2KyZAtXvvP8eV4mIneT3wT2Qdmlw

###
GET http://localhost:5000/files/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3Mzc2Nzc1OTMsImV4cCI6MTczNzY4ODM5M30.ZRAEJtjgLecl7UFQMKdkjPFei79vzOdR541N6Bj0ChA

###
GET http://localhost:5000/files/file/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3Mzc2Nzc1OTMsImV4cCI6MTczNzY4ODM5M30.ZRAEJtjgLecl7UFQMKdkjPFei79vzOdR541N6Bj0ChA